"""Keyboards package."""

from .contact_cta import (
    CONTACT_TRAINER_TEXT,
    CONTACT_TRAINER_URL,
    INSTAGRAM_DM_TEXT,
    INSTAGRAM_DM_URL,
    get_contact_trainer_keyboard,
    get_instagram_dm_keyboard,
)
from .main_menu import (
    BUTTON_ABOUT,
    BUTTON_CONSULT_NO,
    BUTTON_CONSULT_YES,
    BUTTON_CONTACT,
    BUTTON_DIAGNOSTICS,
    BUTTON_DONT_KNOW,
    BUTTON_KEEP,
    BUTTON_NO,
    BUTTON_REENTER,
    BUTTON_RETAKE,
    BUTTON_RESULT_MY_DATA,
    BUTTON_RESULT_REPORT,
    BUTTON_RESULT_UPDATE,
    BUTTON_SEX_MAN,
    BUTTON_SEX_WOMAN,
    BUTTON_SKIP_PRESSURE,
    BUTTON_SKIP_SITTING,
    BUTTON_UPDATE_BOT,
    BUTTON_VIEW_RESULTS,
    BUTTON_YES,
    get_existing_profile_actions_keyboard,
    get_main_menu_keyboard,
    get_post_diagnostics_keyboard,
    get_update_bot_keyboard,
)
from .navigation import BUTTON_BACK, BUTTON_CANCEL, BUTTON_HOME_MENU, BUTTON_SKIP, get_scenario_skip_keyboard

__all__ = (
    "get_contact_trainer_keyboard",
    "get_instagram_dm_keyboard",
    "CONTACT_TRAINER_URL",
    "CONTACT_TRAINER_TEXT",
    "INSTAGRAM_DM_URL",
    "INSTAGRAM_DM_TEXT",
    "BUTTON_ABOUT",
    "BUTTON_BACK",
    "BUTTON_CANCEL",
    "BUTTON_CONTACT",
    "BUTTON_CONSULT_NO",
    "BUTTON_CONSULT_YES",
    "BUTTON_DIAGNOSTICS",
    "BUTTON_DONT_KNOW",
    "BUTTON_HOME_MENU",
    "BUTTON_KEEP",
    "BUTTON_NO",
    "BUTTON_REENTER",
    "BUTTON_RETAKE",
    "BUTTON_RESULT_MY_DATA",
    "BUTTON_RESULT_REPORT",
    "BUTTON_RESULT_UPDATE",
    "BUTTON_SEX_MAN",
    "BUTTON_SEX_WOMAN",
    "BUTTON_SKIP",
    "BUTTON_SKIP_PRESSURE",
    "BUTTON_SKIP_SITTING",
    "BUTTON_UPDATE_BOT",
    "BUTTON_VIEW_RESULTS",
    "BUTTON_YES",
    "get_existing_profile_actions_keyboard",
    "get_main_menu_keyboard",
    "get_post_diagnostics_keyboard",
    "get_update_bot_keyboard",
    "get_scenario_skip_keyboard",
)
